config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: "pages#home"
  get 'weather', to: 'pages#weather'
  get 'profil', to: 'pages#profil'
  get 'live', to: 'pages#live'
  get 'feedback', to: 'pages#feedback'
  get '/users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'

  post '/feedback', to: 'feedback#create'

  resources :races, only: %i[index show new create destroy] do
    resource :waters, only: %i[show]
    resource :progressions, only: %i[show]
  end
end

app/models/water.rb
class Water < ApplicationRecord
end

app/controllers/waters_controller.rb
require 'net/http'
require 'json'

class WatersController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index show] ##a enlever

  def index

  end

  def show
    @race = Race.find(params[:race_id])
    # @water_markers = parse_gpx('db/seeds/fixtures/water_point_angers_nantes.txt')
    @water_markers = api_poi
    @markers = @race.gpx_path
    # @status = @race.status
  end

  private

  def parse_gpx(filepath)
    file = File.open(filepath)
    doc = Nokogiri::XML(file)
    trackpoints = doc.xpath('//xmlns:wpt')
    amenity = trackpoints.map do |wpt|
      {
        lat: wpt.xpath('@lat').to_s.to_f,
        lng: wpt.xpath('@lon').to_s.to_f,
        image_url: helpers.asset_url("icons/bottle_true.svg")
      }
    end
    amenity
  end

  def api_poi
    access_token = ENV['GEOAPIFY']

    # get the user's current location using the geolocation API of the browser
    # latitude = '47.6586772'
    # longitude = '-2.7599079'

    # construct
    # api_url = "https://api.geoapify.com/v2/places?categories=amenity.drinking_water&filter=circle:-1.5768993084440663,47.21595744839796,1000&limit=5&apiKey=#{access_token}"
    api_url = "https://api.geoapify.com/v2/places?categories=amenity.drinking_water&filter=circle:-1.6646715918647903,43.38746478130658,1000&limit=5&apiKey=#{access_token}"

    # make an HTTP GET request to the API url
    uri = URI(api_url)
    response = Net::HTTP.get(uri)

    # parse the JSON response into a Ruby hash
    results = JSON.parse(response)
    # puts results
    # puts results["features"][0]["properties"]["lat"]
    # puts results["features"][0]["properties"]["lon"]
    amenity = results["features"].map do |feature|
      {
        lat: feature["properties"]["lat"],
        lon: feature["properties"]["lon"],
        image_url: helpers.asset_url("icons/bottle_true.svg")
      }
      # puts feature["properties"]["lat"]
      # puts feature["properties"]["lon"]
    end
    amenity
  end
end


def api_poi
  access_token = ENV['GEOAPIFY']

  api_url = "https://api.geoapify.com/v2/places?categories=amenity.drinking_water&filter=circle:-1.6646715918647903,43.38746478130658,1000&limit=5&apiKey=#{access_token}"

  # make an HTTP GET request to the API url
  uri = URI(api_url)
  response = Net::HTTP.get(uri)

  # parse the JSON response into a Ruby hash
  results = JSON.parse(response)
  amenity = results["features"].map do |feature|
    {
      lat: feature["properties"]["lat"],
      lon: feature["properties"]["lon"],
      image_url: helpers.asset_url("icons/bottle_true.svg")
    }
  end
  amenity
end

app/views/waters/show.html.erb
<div class = "map-live">
  <div style="width: 100%; height: 92vh;"
    data-controller="mergemaps"
    data-mergemaps-racepoints-value="<%= @markers %>"
    data-mergemaps-waterpoints-value="<%= @water_markers.to_json %>"
    data-mergemaps-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  
<div data-controller="play">
  <%= link_to new_race_path do %>
    <div class="menu-map-top">
        <p style ="margin-top: -3px; margin-right: 15px;"><%= @race.name %></p>
    </div>
  <% end %>

  <div class="menu-map-bottom">

      <h5><% if  @race.started_at == nil %>
            <%= link_to "" do %>
            <% end %>

        <%# <i class="fa-regular fa-square-check"></i> %>
      <% else %>
        <i class="fa-regular fa-square"></i>
      <% end%></h5>
    <div class="menu-map-bottom-direction">
      <h5><% if  @race.started_at == nil %>
        <%= link_to "" do %>
        <%= image_tag("icons/direction.svg",  size: "40x40") %>
        <% end %>
        <%# <i class="fa-regular fa-square-check"></i> %>
      <% else %>
        <i class="fa-regular fa-square"></i>
      <% end%></h5>
      <p>Localisation</p>
    </div>
    <div class="menu-map-bottom-play" data-action="click->play#toggle">
        <%= image_tag("play.svg",  size: "40x40", data: {action: "click->play#start", play_target: "icon"}, class: "play-button") %>
        <%= image_tag("pause.svg",  size: "40x40", data: {action: "click->play#start", play_target: "pause"}, class: "pause-button d-none") %>

      <p><div data-play-target="switchstart">Démarrer</div></p>
      <p><div data-play-target="switchpause" class="d-none">Pause</div></p>
    </div>
  </div>

  <div class="menu-map-bottom-progression">
            <%= link_to race_progressions_path(@race) do %>
            <%= image_tag("icons/person-biking.svg",  size: "40x40") %>
            <% end %>
      <p>Progression</p>
  </div>
</div>
</div>