config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: "pages#home"
  get 'weather', to: 'pages#weather'
  get 'profil', to: 'pages#profil'
  get 'live', to: 'pages#live'
  get 'feedback', to: 'pages#feedback'
  get '/users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'

  post '/feedback', to: 'feedback#create'

  resources :races, only: %i[index show new create destroy] do
    resource :waters, only: %i[show]
    resource :progressions, only: %i[show]
  end
end

app/views/pages/feedback.html.erb
<div class="container-feedback">
  <div class="test">
		<h3>Bienvenue</h3>
	</div>

  <div class="p-feedback">
    <p>Nous souhaitons vous offrir <b>la meilleure expérience possible.</b> C'est pourquoi nous vous encourageons à nous faire part de vos commentaires et de vos suggestions d’améliorations.</p>
    <p>Merci pour votre aide !</p>
    <p><b>Céline, Denis & Pierre.</b></p>
  </div>

  <div class="form-feedback">
    <%= form_with model: Feedback.new, url: feedback_path, method: :post do |form| %>

      <%= form.text_field :name, placeholder: 'Prénom & Nom' %>

      <%= form.email_field :email, placeholder: 'Adresse e-mail' %>

      <%= form.text_area :suggestion, placeholder: 'Commentaires' %>

      <%= form.submit 'Envoyer' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="home-title">

    <div class="titre">
      <h1>Ultra Companion</h1>
    </div>

    <h2>Keep your mind focus on your race !</h2>

  </div>

  <%= link_to "Explorer", live_path, class: "home-button" %>
</div>

app/views/pages/live.html.erb
<div id="map-container" style="width: 100%; height: 92vh;"
  data-controller="live"
  data-live-geoapify-api-key-value="<%= ENV['GEOAPIFY'] %>"
  data-live-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div class="marker"></div>
</div>

<div data-controller="play">
  <%# <%= link_to new_race_path do %>
    <%# <div class="menu-map-top"> %>
      <%# <div style ="margin-top: 7px;"> %>
        <%# <%=image_tag("icons/upload.svg")%>
      <%# </div> %>
      <%# <div>
        <p style ="margin-top: -3px; margin-right: 15px;">Ajouter mon parcours</p>
      </div>
    </div>
  <% end %>

  <div class="menu-map-bottom">
    <div class="menu-map-bottom-direction">
        <%= link_to "" do %>
          <%= image_tag("icons/gps.svg",  size: "40x40") %>
        <% end %>
  </div>
</div>
</div>

app/views/pages/profil.html.erb
<div class = "container-profil " >
	<div class="test">
		<h3>Profile</h3>
	</div>
</div>


<div class = "card-profil">
    <div class="center-avatar">
      <div class="avatar2">
      </div>
    </div>

    <div style ="text-align: center; margin-top:10px">
      <h4>Pierre, 34 ans</h4>
      <p><%= @races %> <strong>courses</strong>   <i class="fa-solid fa-flag-checkered"></i></p>
    </div>

    <div class="white-card" style="margin-top:20px; margin-bottom:20px;">
      <p>Passionné de velo et plus particulièrement de VTT depuis tout jeune. J’aspire à de nouveaux défis pour me ressourcer et partager le plaisir de la route.</p>
    </div>
</div>

    <div class="setup" style="margin-left: 30px; margin-right:25px">
      <div class="set">
        <%= link_to image_tag("icons/param.svg")%>
        Paramètres
      </div>
      <div class="deconect" style="margin-top:15px">
        <%= link_to image_tag("icons/deconect.svg")%>

        <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
        <%# A TESTER %>

      </div>
    </div>

app/views/pages/races_done.html.erb
  <%# la page de présentation de chacune des courses réalisées %>
  <%# Afficher la carte du parcours - Automatiser en présentant la bonne page%>
  <div
    style="width: 100%; height: 300px; box-shadow: 0 4px 2px -2px gray;"
    data-controller="map"
    data-map-markers-value="<%= @markers %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <%# Automatiser le nom de la course  %>
  <div>
    <h3>Nom de la course</h3>
  </div>

  <div class="white-card">

    <div>
      <%=image_tag("icons/bike.svg")%>
      <p style="margin-top: 3px">1 000 km</p> <%# # Ajouter ici une automatisation depuis seed %>
    </div>
    <div>
      <%=image_tag("icons/denivele.svg")%>
      <p style="margin-top: 3px">20 000 m</p> <%# # Ajouter ici une automatisation depuis seed %>
    </div>
    <div>
      <%=image_tag("icons/clock.svg")%>
      <p style="margin-top: 3px">90 h</p> <%# # Ajouter ici une automatisation depuis seed %>
    </div>

  </div>


  <div class="white-card-companion">
    <div style="margin-left : 10px;" >
      <div>
        <h5><strong>Profil de la course</strong></h5>
      </div >
      <div>
      <%=image_tag("profil.png")%>
      </div>
        <%# Avoir le profil de chaque course dans les seed %>
    </div>
  </div>

app/views/pages/weather.html.erb
<div class="container-weather">

  <div class="test">
		<h3>Météo</h3>
	</div>

  <div class="content" data-controller="weather"
  data-weather-api-key-value="<%= ENV['OPENWEATHER_API_KEY'] %>">
    <form class="ligne" data-action="submit->weather#fetchWeather">
      <input type="text" placeholder="Ville" class="formulaire" data-weather-target="input">
      <a href="" class="position" data-action="click->weather#fetchWeatherByCoordinates"><i class="bi bi-geo-alt"></i></a>
      <input type="submit" value="Météo" class="btn btn-primary">
    </form>

  <div class="carousel-meteo">

    <div class="card-principal">
      <h1><span data-weather-target="city"></span></h1>
      <div>
        <%# <p data-weather-target="description"></p> %>
        <p data-weather-target="date"></p>

        <div class="d-flex">
          <img src="" alt="" data-weather-target="icon">
          <h2 data-weather-target="temperature"></h2>
        </div>
      </div>
    </div>

    <div class="card-principal">
      <h1><span data-weather-target="city"></span></h1>
      <div>
        <%# <p data-weather-target="description"></p> %>
        <p data-weather-target="date"></p>

        <div class="d-flex">
          <img src="" alt="" data-weather-target="icon">
          <h2 data-weather-target="temperature"></h2>
        </div>
      </div>
    </div>

    <div class="card-principal">
      <h1><span data-weather-target="city"></span></h1>
      <div>
        <%# <p data-weather-target="description"></p> %>
        <p data-weather-target="date"></p>
        <div class="d-flex">
          <img src="" alt="" data-weather-target="icon">
          <h2 data-weather-target="temperature"></h2>
        </div>
      </div>
    </div>

      <div class="card-principal">
      <h1><span data-weather-target="city"></span></h1>
      <div>
        <%# <p data-weather-target="description"></p> %>
        <p data-weather-target="date"></p>
        <div class="d-flex">
          <img src="" alt="" data-weather-target="icon">
          <h2 data-weather-target="temperature"></h2>
        </div>
      </div>
    </div>

    <div class="card-principal">
      <h1><span data-weather-target="city"></span></h1>
      <div>
        <%# <p data-weather-target="description"></p> %>
        <p data-weather-target="date"></p>
        <div class="d-flex">
          <img src="" alt="" data-weather-target="icon">
          <h2 data-weather-target="temperature"></h2>
        </div>
      </div>
    </div>

    <div class="card-principal">
      <h1><span data-weather-target="city"></span></h1>
      <div>
        <%# <p data-weather-target="description"></p> %>
        <p data-weather-target="date"></p>
        <div class="d-flex">
          <img src="" alt="" data-weather-target="icon">
          <h2 data-weather-target="temperature"></h2>
        </div>
      </div>
    </div>

</div>

  </div>
</div>