config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  root to: "pages#home"
  get 'weather', to: 'pages#weather'
  get 'profil', to: 'pages#profil'
  get 'live', to: 'pages#live'
  get 'feedback', to: 'pages#feedback'
  get '/users/auth/google_oauth2/callback', to: 'users/omniauth_callbacks#google_oauth2'

  post '/feedback', to: 'feedback#create'

  resources :races, only: %i[index show new create destroy] do
    resource :waters, only: %i[show]
    resource :progressions, only: %i[show]
  end
end

app/models/progression.rb
class Progression < ApplicationRecord
end

app/controllers/progressions_controller.rb
class ProgressionsController < ApplicationController

  def show
    @race = Race.find(params[:race_id])
    @markers = @race.gpx_path
    @elevations = @race.elevations
    
  end

  private

  # parsing du fichier pour afficher la carte et le parcours sur la page
  # def parse_gpx(file)
  #   # file = File.open(filepath)
  #   doc = Nokogiri::XML(file)
  #   trackpoints = doc.xpath('//xmlns:trkpt')
  #   route = trackpoints.map do |trkpt|
  #     lat = trkpt.xpath('@lat').to_s.to_f
  #     lng = trkpt.xpath('@lon').to_s.to_f
  #     [lng, lat]
  #   end
  #   route
  # end

  # parsing du fichier pour obtenir les valeurs de l'élévation
  # def elevation_parse(file)
  #   # file = File.open(filepath)
  #   doc = Nokogiri::XML(file)
  #   trackpoints = doc.xpath('//xmlns:ele')
  #   elevation = trackpoints.map do |trkpt|
  #     trkpt.text.strip.to_f
  #   end
  #   elevation
  # end



  def race_params
    params.require(:race).permit(:name, :date, :started_at)
  end

  def set_race
    @race = Race.find(params[:id])
  end
end

app/views/progressions/show.html.erb
  <%# Afficher le parcours %>
  <div class="map-live">
    <div style="width: 100%; height: 300px; box-shadow: 0 4px 2px -2px gray;"
      data-controller="map"
      data-map-markers-value="<%= @markers %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
      <div class="menu-map-bottom-navigation">
        <h5><%= link_to race_waters_path(@race) do %>
          <%= image_tag("icons/navigation.svg",  size: "40x40") %>
          <% end %></h5>
        <p>Navigation</p>
      </div>
    </div>
  </div>

  <div class="card-live-description">
    <%# Afficher le nom de la course %>
    <div class="race-name">
      <h3><%= @race.name%></h3>
    </div>

    <%# Avancer en temps et distance de l'utilisateur %>
  <div class="race-summary">
    <div>
      <%=image_tag("icons/bike.svg")%> <p style="margin-top: 3px; font-size: 0.8rem">
    </div>
    <div>
      <strong><%= @distances %> km </strong></p>
    </div>
    <div>
      <%=image_tag("icons/denivele.svg")%><p style="margin-top: 3px; font-size: 0.8rem">
    </div>
    <div>
      <strong><%= @gains %> m </strong></p>
    </div>
  </div>

    <%# Profil de la course %>
    <div class="white-card-companion">
      <div style="margin-left: 10px;" >
        <div>
          <h5><strong>Profil de la course</strong></h5>
        </div >
        <div>
          <%= area_chart @elevations.map.with_index{|idx, ele| [ele, idx]}, min: 0, xmin: 0, xmax: 6500, points: false, colors: ["#245611", "#666"], width: "auto", height: "25vh" %>
        </div>
      </div>
    </div>
  </div>